# Generated by Django 3.1.7 on 2021-04-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20210425_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(default='icon.png', upload_to='books/'),
        ),
    ]
