# Generated by Django 3.1.7 on 2021-04-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0002_auto_20210408_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='editorial/')),
            ],
        ),
        migrations.CreateModel(
            name='Editorial_Audiobooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiobook', models.FileField(upload_to='audiobook_editorial/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Audiobooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiobook', models.FileField(upload_to='audiobook_book/')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='convert.books')),
            ],
        ),
    ]
