# Generated by Django 3.1.7 on 2021-05-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0005_auto_20210425_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapters',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='editorial_audiobooks',
            name='title',
        ),
        migrations.AddField(
            model_name='books',
            name='index',
            field=models.TextField(default='0: ', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to='books'),
        ),
        migrations.DeleteModel(
            name='AudioBook',
        ),
        migrations.DeleteModel(
            name='Chapters',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.DeleteModel(
            name='Editorial_Audiobooks',
        ),
    ]
