# Generated by Django 3.1.7 on 2021-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0007_auto_20210529_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='index',
            field=models.CharField(default='', max_length=100),
        ),
    ]
