# Generated by Django 3.1.6 on 2021-05-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0010_auto_20210530_0603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editorial',
        ),
        migrations.AlterField(
            model_name='books',
            name='index',
            field=models.CharField(default='Editorial', max_length=100),
        ),
    ]
