# Generated by Django 3.1.6 on 2021-05-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert', '0011_auto_20210530_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='index',
            field=models.CharField(default='editorial', max_length=100),
        ),
    ]
